### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by NameOfTheDragon** [remy/mit-license#1451]
Oops, it looks like there's a server issue...

![image](https://user-images.githubusercontent.com/1268490/102079057-e69ffa00-3e03-11eb-96a7-7f2aa1f84318.png)

**Comment by Richienb** [comment]
@remy

**Comment by remy** [comment]
Looks like it's crashing quite often:

<img width="1224" alt="Screenshot 2020-12-14 at 16 10 11" src="https://user-images.githubusercontent.com/13700/102105110-e6fdbc80-3e26-11eb-9651-6439a0f7ac61.png">


```
2020-12-14T16:08:26.360267+00:00 app[web.1]: /app/routes/get.js:63
2020-12-14T16:08:26.360276+00:00 app[web.1]: if (user.copyright) {
2020-12-14T16:08:26.360278+00:00 app[web.1]: ^
2020-12-14T16:08:26.360278+00:00 app[web.1]:
2020-12-14T16:08:26.360279+00:00 app[web.1]: TypeError: Cannot read property 'copyright' of undefined
2020-12-14T16:08:26.360280+00:00 app[web.1]: at module.exports (/app/routes/get.js:63:12)
2020-12-14T16:08:26.360281+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-12-14T16:08:26.360282+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-12-14T16:08:26.360283+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2020-12-14T16:08:26.360283+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-12-14T16:08:26.360284+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2020-12-14T16:08:26.360284+00:00 app[web.1]: at param (/app/node_modules/express/lib/router/index.js:354:14)
2020-12-14T16:08:26.360284+00:00 app[web.1]: at param (/app/node_modules/express/lib/router/index.js:365:14)
2020-12-14T16:08:26.360285+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
2020-12-14T16:08:26.360285+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
```

**Comment by remy** [comment]
@Richienb didn't you do a refactor recently?

**Comment by Richienb** [comment]
@remy I did one three months ago.

**Comment by Richienb** [comment]
This issue only happens periodically - I am unable to reproduce it consistently.

**Comment by Richienb** [comment]
I (think I) found the problem: It's all to do with a Javascript quirk.

Here we assign `response.locals.user` by extending itself with the result of a promise.

https://github.com/remy/mit-license/blob/aa280a646bbc0f1ffa74aeee86557e3cfc02c224/middleware/load-user.js#L17-L20

Notice that we await it within the assignment. What do you think `response.locals.user` looks like while the promise is still pending?

It actually temporarily sets it to what is essentially `undefined`.

To fix it, we just need to await the data before the assignment:

https://github.com/remy/mit-license/blob/6d916f436e31c7ad01c96c5aabd9ffb18453137d/middleware/load-user.js#L17-L22

I've just set up a quick [uptime page](https://stats.uptimerobot.com/5RnZKu0ok8) so we can track if this change did anything.

**Comment by remy** [comment]
At a guess, the get router is getting the user object as undefined (via an
incorrect cname lookup) and has been crashing regularly. Maybe an object
test before that (or similar) lines.

**Comment by Richienb** [comment]
cname lookup?

**Comment by remy** [comment]
Sorry, we're crossing messages. 

That await won't return the user object until the promise has settled (so the refactor here shouldn't make any difference).

The user object is definitely undefined. If it were set to a promise it would pass the test for `user.cooyright` (because we can do prop lookups on a promise - regardless of whether the promise has settled or not).

**Comment by NameOfTheDragon** [comment]
It seems to be working again now.

**Comment by remy** [comment]
Yes, but it'll crash again. There's a bug that causes it to trip and crash.

**Comment by Busaruba2011** [comment]
It's happened again today. 3/2/21 at 3:38 GMT
![Screenshot (47)](https://user-images.githubusercontent.com/65495333/106770472-ebc83b00-6635-11eb-8d80-dfa1a38ece88.png)

**Comment by okyanusoz** [comment]
It's OK now I think.

**Comment by Richienb** [comment]
The last recorded downtime is on February 11, 2021. I believe this means the issue is now resolved.
